### ISSUE TITLE
[core:getter], replace read() and write() with recvMsg() and sendMsg

### ISSUE THREAD

**Issue by StefanoBelli** [AlessandroSpallina/JASM#103]
ssize_t recvMsg(int,char*);
ssize_t sendMsg(int,char[]);

**Comment by StefanoBelli** [comment]
#### WARNING

will not proceed until src/core/getter.c will be updated as the title says 

#### Meanwhile

QJasm is in development :D

**Comment by AlessandroSpallina** [comment]
done
