### ISSUE TITLE
Multiple auth retries to redefine

### ISSUE THREAD

**Issue by StefanoBelli** [AlessandroSpallina/JASM#82]

**Comment by StefanoBelli** [comment]
Server just writes a message to client which says something like "maxconnreached" -> in for cycle (where is used CONFIG_MAX_AUTH_TRIES)

**Comment by StefanoBelli** [comment]
My Task! :)

**Comment by AlessandroSpallina** [comment]
please, test if this happen again

**Comment by StefanoBelli** [comment]
## Less Priority

Closing...
